/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccesRouteImport } from './routes/acces'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CaisseRouteImport } from './routes/caisse'
import { Route as CuisineRouteImport } from './routes/cuisine'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGeranceRouteImport } from './routes/_authenticated/gerance'
import { Route as TTableRouteImport } from './routes/t.$table'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesRoute = AccesRouteImport.update({
  id: '/acces',
  path: '/acces',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CaisseRoute = CaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisineRoute = CuisineRouteImport.update({
  id: '/cuisine',
  path: '/cuisine',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGeranceRoute = AuthenticatedGeranceRouteImport.update({
  id: '/gerance',
  path: '/gerance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TTableRoute = TTableRouteImport.update({
  id: '/t/$table',
  path: '/t/$table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acces': typeof AccesRoute
  '/auth': typeof AuthRoute
  '/caisse': typeof CaisseRoute
  '/cuisine': typeof CuisineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gerance': typeof AuthenticatedGeranceRoute
  '/t/$table': typeof TTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acces': typeof AccesRoute
  '/auth': typeof AuthRoute
  '/caisse': typeof CaisseRoute
  '/cuisine': typeof CuisineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gerance': typeof AuthenticatedGeranceRoute
  '/t/$table': typeof TTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acces': typeof AccesRoute
  '/auth': typeof AuthRoute
  '/caisse': typeof CaisseRoute
  '/cuisine': typeof CuisineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gerance': typeof AuthenticatedGeranceRoute
  '/t/$table': typeof TTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acces'
    | '/auth'
    | '/caisse'
    | '/cuisine'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/gerance'
    | '/t/$table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acces'
    | '/auth'
    | '/caisse'
    | '/cuisine'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/gerance'
    | '/t/$table'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acces'
    | '/auth'
    | '/caisse'
    | '/cuisine'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/gerance'
    | '/t/$table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccesRoute: typeof AccesRoute
  AuthRoute: typeof AuthRoute
  CaisseRoute: typeof CaisseRoute
  CuisineRoute: typeof CuisineRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TTableRoute: typeof TTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acces': {
      id: '/acces'
      path: '/acces'
      fullPath: '/acces'
      preLoaderRoute: typeof AccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caisse': {
      id: '/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof CaisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisine': {
      id: '/cuisine'
      path: '/cuisine'
      fullPath: '/cuisine'
      preLoaderRoute: typeof CuisineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerance': {
      id: '/_authenticated/gerance'
      path: '/gerance'
      fullPath: '/gerance'
      preLoaderRoute: typeof AuthenticatedGeranceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/t/$table': {
      id: '/t/$table'
      path: '/t/$table'
      fullPath: '/t/$table'
      preLoaderRoute: typeof TTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGeranceRoute: typeof AuthenticatedGeranceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGeranceRoute: AuthenticatedGeranceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccesRoute: AccesRoute,
  AuthRoute: AuthRoute,
  CaisseRoute: CaisseRoute,
  CuisineRoute: CuisineRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TTableRoute: TTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
